branches:
  only: master

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      sudo: true
      dist: trusty
      before_install:
        - chmod +x mvnw

deploy:
  provider: heroku
  api_key:
    secure: 479753d1-9055-4afa-9198-ddc28927a510