branches:
  only: master

matrix:
  include:
    - language: java
      jdk: oraclejdk8

    - language: node_js
      node_js: stable
      install:
        - npm install
      before_install:
        - cd ./frontend/
      script:
        - npm run build

deploy:
  provider: heroku
  api_key:
    secure: